# Generated by Django 4.1.2 on 2022-11-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user-form',
            },
        ),
    ]
