# Generated by Django 4.1.2 on 2022-11-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataform',
            name='active',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
