# Generated by Django 4.1.2 on 2022-11-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_userdataform_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDataForm',
            new_name='UserData',
        ),
    ]
